language: r
r: release
sudo: required

os: osx      
osx_image: xcode8.2

before_install:
    - pwd
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    
install:
    - sudo chown -R $(whoami) /usr/local/share/man/man7
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install unixodbc ; fi
    - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
    
r_binary_packages: RODBC
